### ISSUE TITLE
What is the reason for setting the label/s to 50?

### ISSUE THREAD

**Issue by jp1924** [mkunes/w2v2_audioFrameClassification#4]
Is the reason for setting the Feature Encoder of Wav2Vec2 to 50 considering that it compresses audio in 20ms increments? When I actually passed a 20-second audio with 16,000 samples through Wav2Vec2, I obtained around 1,000 Time values, so I'm assuming that's the case. Or is there another reason?

**Comment by mkunes** [comment]
Yes. wav2vec2 has a stride of 20ms (or, to be precise, 320 samples, which is 20ms at 16kHz), so by default, the [Wav2Vec2ForAudioFrameClassification](https://huggingface.co/docs/transformers/model_doc/wav2vec2#transformers.Wav2Vec2ForAudioFrameClassification) class in Transformers (which is what's being used here) will output 50 values per one second of speech.

The entire output will be one value shorter though (only 999 values for 20s of speech). I believe this is because the actual audio context is larger (25ms?), but I've never looked into it.
